---
name: Flowzone
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master]
jobs:
  flowzone:
    name: Flowzone
    if: |
      (github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request') ||
      (github.event.pull_request.head.repo.full_name != github.repository && github.event_name == 'pull_request_target')
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with: {}
